### ISSUE TITLE
Does this suite support nfs v4.1?

### ISSUE THREAD

**Issue by AlexKingGo** [soumyakoduri/nfs-test-suite#1]
hello Soumya Koduri, could you please answer me that whether this suite support nfs v4.1?

**Comment by soumyakoduri** [comment]
Hi,
Its been very long time since I have used this test-suite. If the version specified is "4", we seem to be mounting with "-o vers=4" mount option. Since there is no minor version specified, depending on your client machine OS version, it may default to v4.1 or v4.2.

Please check the same and let me know if you run into any issues.
